# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from tide_date.v1 import api_pb2 as tide__date_dot_v1_dot_api__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in tide_date/v1/api_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TideDateServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Now = channel.unary_unary(
                '/tide.api.tidedate.TideDateService/Now',
                request_serializer=tide__date_dot_v1_dot_api__pb2.NowRequest.SerializeToString,
                response_deserializer=tide__date_dot_v1_dot_api__pb2.NowResponse.FromString,
                _registered_method=True)
        self.NowError = channel.unary_unary(
                '/tide.api.tidedate.TideDateService/NowError',
                request_serializer=tide__date_dot_v1_dot_api__pb2.NowErrorRequest.SerializeToString,
                response_deserializer=tide__date_dot_v1_dot_api__pb2.NowErrorResponse.FromString,
                _registered_method=True)


class TideDateServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Now(self, request, context):
        """生成当前时间
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def NowError(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TideDateServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Now': grpc.unary_unary_rpc_method_handler(
                    servicer.Now,
                    request_deserializer=tide__date_dot_v1_dot_api__pb2.NowRequest.FromString,
                    response_serializer=tide__date_dot_v1_dot_api__pb2.NowResponse.SerializeToString,
            ),
            'NowError': grpc.unary_unary_rpc_method_handler(
                    servicer.NowError,
                    request_deserializer=tide__date_dot_v1_dot_api__pb2.NowErrorRequest.FromString,
                    response_serializer=tide__date_dot_v1_dot_api__pb2.NowErrorResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tide.api.tidedate.TideDateService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('tide.api.tidedate.TideDateService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TideDateService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Now(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tide.api.tidedate.TideDateService/Now',
            tide__date_dot_v1_dot_api__pb2.NowRequest.SerializeToString,
            tide__date_dot_v1_dot_api__pb2.NowResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def NowError(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tide.api.tidedate.TideDateService/NowError',
            tide__date_dot_v1_dot_api__pb2.NowErrorRequest.SerializeToString,
            tide__date_dot_v1_dot_api__pb2.NowErrorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
