# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tide_date/v1/api.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'tide_date/v1/api.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2
from types import error_pb2 as types_dot_error__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16tide_date/v1/api.proto\x12\x11tide.api.tidedate\x1a google/protobuf/descriptor.proto\x1a\x11types/error.proto\"?\n\nNowRequest\x12\x1d\n\nrequest_id\x18\x01 \x01(\tR\tRequestId\x12\x12\n\x04\x64\x61ta\x18\x02 \x01(\x0cR\x04\x44\x61ta\"n\n\x0bNowResponse\x12\x1d\n\nrequest_id\x18\x01 \x01(\tR\tRequestId\x12\x12\n\x04\x64\x61te\x18\x02 \x01(\tR\x04\x44\x61te\x12,\n\x05\x65rror\x18\xe8\x07 \x01(\x0b\x32\x15.tide.api.types.ErrorR\x05\x45rror\"0\n\x0fNowErrorRequest\x12\x1d\n\nrequest_id\x18\x01 \x01(\tR\tRequestId\"s\n\x10NowErrorResponse\x12\x1d\n\nrequest_id\x18\x01 \x01(\tR\tRequestId\x12\x12\n\x04\x64\x61te\x18\x02 \x01(\tR\x04\x44\x61te\x12,\n\x05\x65rror\x18\xe8\x07 \x01(\x0b\x32\x15.tide.api.types.ErrorR\x05\x45rror2\xb0\x01\n\x0fTideDateService\x12\x46\n\x03Now\x12\x1d.tide.api.tidedate.NowRequest\x1a\x1e.tide.api.tidedate.NowResponse\"\x00\x12U\n\x08NowError\x12\".tide.api.tidedate.NowErrorRequest\x1a#.tide.api.tidedate.NowErrorResponse\"\x00\x42#\n\x1f\x63om.kaydxh.tide.api.tidedate.v1P\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tide_date.v1.api_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\037com.kaydxh.tide.api.tidedate.v1P\001'
  _globals['_NOWREQUEST']._serialized_start=98
  _globals['_NOWREQUEST']._serialized_end=161
  _globals['_NOWRESPONSE']._serialized_start=163
  _globals['_NOWRESPONSE']._serialized_end=273
  _globals['_NOWERRORREQUEST']._serialized_start=275
  _globals['_NOWERRORREQUEST']._serialized_end=323
  _globals['_NOWERRORRESPONSE']._serialized_start=325
  _globals['_NOWERRORRESPONSE']._serialized_end=440
  _globals['_TIDEDATESERVICE']._serialized_start=443
  _globals['_TIDEDATESERVICE']._serialized_end=619
# @@protoc_insertion_point(module_scope)
